# Placeholder for secrets buildspec using TruffleHog
# A solution document can be found within the solutions directory.
#
# Within this file, you should have the following phases and instructions:
# 1. install:
#    - Install TruffleHog (https://github.com/trufflesecurity/trufflehog#floppy_disk-installation)
# 2. pre_build:
#    - Confirm TruffleHog is installed
# 3. build:
#    - Scan all artifacts files for secrets
# 4. (Optional) post_build:
#    - Print the results/date of the scan
# 5. artifacts:
#    - Upload the results of the scan to the build output
