version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install --quiet cfn-lint pyyaml boto3
  build:
    commands:
      - echo "[1/2] Checking cfn-lint version..."
      - cfn-lint --version
      - echo "[2/2] Running cfn-lint against all templates..."
      - cfn-lint -f pretty infra/**/*.yml

artifacts:
  files:
    - "**/*"
