version: 0.2

phases:
  install:
    commands:
      - echo "[1/3]Installing TruffleHog to home directory..."
      - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  pre_build:
    commands:
      - echo "[2/3] Confirming TruffleHog is installed..."
      - trufflehog --version
  build:
    commands:
      - echo "[3/3] Scanning all artifacts files for secrets..."
      - echo "TruffleHog scan started on $(date)"
      - trufflehog filesystem ./* --fail
  post_build:
    commands:
      - echo "TruffleHog scan completed on $(date)"

artifacts:
  files:
    - "**/*"
